name: Tests CI

# Ejecutar en push a main/master y en pull requests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    # Checkout del c贸digo
    - name: Checkout c贸digo
      uses: actions/checkout@v4

    # Configurar Node.js
    - name: Configurar Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Instalar dependencias
    - name: Instalar dependencias
      run: npm ci

    # Ejecutar tests unitarios
    - name: Ejecutar tests unitarios
      run: npm run test:unit

    # Ejecutar tests de integraci贸n
    - name: Ejecutar tests de integraci贸n
      run: npm run test:integration
